services:
  - type: web
    name: zerodha-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install
    startCommand: npm start
    plan: free

  - type: web
    name: zerodha-dashboard
    env: node
    rootDir: dashboard
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free

  - type: web
    name: zerodha-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    plan: free